"""add acronym to kb_organizations

Revision ID: 0a9bf1357f15
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 22:46:05.379381

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9bf1357f15'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_organizations', sa.Column('acronym', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_organizations', 'acronym')
    # ### end Alembic commands ###
