"""add unique constraint to articles url

Revision ID: 0ac52fd57a86
Revises: 2305a298193f
Create Date: 2026-01-16 23:51:26.774347

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac52fd57a86'
down_revision = '2305a298193f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=False)
    # ### end Alembic commands ###
