"""add story edges table

Revision ID: 149f623c3b4a
Revises: 17c2ed7d42ba
Create Date: 2026-02-25 16:42:17.262330

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149f623c3b4a'
down_revision = '17c2ed7d42ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_edges',
    sa.Column('from_story_id', sa.String(), nullable=False),
    sa.Column('to_story_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['to_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('from_story_id', 'to_story_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_edges')
    # ### end Alembic commands ###
