"""add date_added and validated to kb_entities, validated to story_entities

Revision ID: 20f47070c168
Revises: 6a6513b38fdf
Create Date: 2026-04-26 19:42:50.882713

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f47070c168'
down_revision = '6a6513b38fdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_entities', sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('kb_entities', sa.Column('validated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('story_entities', sa.Column('validated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_entities', 'validated')
    op.drop_column('kb_entities', 'validated')
    op.drop_column('kb_entities', 'date_added')
    # ### end Alembic commands ###
