"""add article_embeddings table

Revision ID: 2305a298193f
Revises: 02649bb39883
Create Date: 2026-01-16 23:48:48.008791

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '2305a298193f'
down_revision = '02649bb39883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_embeddings',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('embedded_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'embedding_model')
    )
    op.drop_column('articles', 'embedded_text')
    op.drop_column('articles', 'embedding_model')
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('embedding_model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('embedded_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('article_embeddings')
    # ### end Alembic commands ###
