"""added article locations table

Revision ID: 23117ec3c308
Revises: a2a445ee9c97
Create Date: 2026-02-01 12:12:30.616828

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23117ec3c308'
down_revision = 'a2a445ee9c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_locations',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['wikidata_qid'], ['locations.wikidata_qid'], ),
    sa.PrimaryKeyConstraint('article_id', 'wikidata_qid', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_locations')
    # ### end Alembic commands ###
