"""add timeseries tables

Revision ID: 26294d82c169
Revises: cc22131966f1
Create Date: 2026-03-08 18:32:09.525277

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26294d82c169'
down_revision = 'cc22131966f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ts_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ts_indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['ts_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts_datapoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['ts_entities.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['ts_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'entity_id', 'date', name='uq_ts_datapoint')
    )
    op.create_index('ix_ts_datapoints_date', 'ts_datapoints', ['date'], unique=False)
    op.create_index('ix_ts_datapoints_indicator_entity', 'ts_datapoints', ['indicator_id', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ts_datapoints_indicator_entity', table_name='ts_datapoints')
    op.drop_index('ix_ts_datapoints_date', table_name='ts_datapoints')
    op.drop_table('ts_datapoints')
    op.drop_table('ts_indicators')
    op.drop_table('ts_sources')
    op.drop_table('ts_entities')
    # ### end Alembic commands ###
