"""added story topic table

Revision ID: 2b20377b3680
Revises: df794d331489
Create Date: 2026-02-02 12:57:08.487806

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b20377b3680'
down_revision = 'df794d331489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_topics',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_topics')
    # ### end Alembic commands ###
