"""added person tables

Revision ID: 38c40ca77dc9
Revises: 2b20377b3680
Create Date: 2026-02-07 10:07:52.704264

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c40ca77dc9'
down_revision = '2b20377b3680'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nationalities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('wikidata_qid')
    )
    op.create_table('article_persons',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['wikidata_qid'], ['persons.wikidata_qid'], ),
    sa.PrimaryKeyConstraint('article_id', 'wikidata_qid', 'name')
    )
    op.create_table('person_aliases',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wikidata_qid'], ['persons.wikidata_qid'], ),
    sa.PrimaryKeyConstraint('alias', 'wikidata_qid')
    )
    op.create_table('story_persons',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['wikidata_qid'], ['persons.wikidata_qid'], ),
    sa.PrimaryKeyConstraint('story_id', 'wikidata_qid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_persons')
    op.drop_table('person_aliases')
    op.drop_table('article_persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
