"""add tg_intel tables

Revision ID: 3d34e97c7f70
Revises: a3f1c9d82e05
Create Date: 2026-04-18 15:11:20.801421

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d34e97c7f70'
down_revision = 'a3f1c9d82e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tg_cursors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=False),
    sa.Column('backfill_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('tg_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tg_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_tg_channel_message')
    )
    op.create_index(op.f('ix_tg_posts_channel_id'), 'tg_posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tg_posts_date'), 'tg_posts', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_posts_date'), table_name='tg_posts')
    op.drop_index(op.f('ix_tg_posts_channel_id'), table_name='tg_posts')
    op.drop_table('tg_posts')
    op.drop_table('tg_cursors')
    op.drop_table('tg_channels')
    # ### end Alembic commands ###
