"""add locations

Revision ID: 62843a4bf2f7
Revises: d86eedd533e3
Create Date: 2026-01-31 04:38:15.447650

"""
from __future__ import annotations

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62843a4bf2f7'
down_revision = 'd86eedd533e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_locations_coordinates "
        "ON locations USING gist (coordinates)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_coordinates', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    # ### end Alembic commands ###
