"""add_display_name_to_ts_sources

Revision ID: 6a6513b38fdf
Revises: e2f94a7b1c85
Create Date: 2026-04-26 12:49:02.173870

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6513b38fdf'
down_revision = 'e2f94a7b1c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ts_sources', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ts_sources', 'display_name')
    # ### end Alembic commands ###
