"""add article_entity counts

Revision ID: 790ba4214468
Revises: 7f6af21de1ac
Create Date: 2026-01-18 23:45:46.121555

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790ba4214468'
down_revision = '7f6af21de1ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_entities', sa.Column('entity_count', sa.Integer(), nullable=False))
    op.add_column('article_entities', sa.Column('entity_in_article_title', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_entities', 'entity_in_article_title')
    op.drop_column('article_entities', 'entity_count')
    # ### end Alembic commands ###
