"""add article clusters

Revision ID: 7f6af21de1ac
Revises: 0ac52fd57a86
Create Date: 2026-01-18 14:25:05.558979

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6af21de1ac'
down_revision = '0ac52fd57a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_clusters',
    sa.Column('article_cluster_id', sa.String(), nullable=False),
    sa.Column('clustered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('article_cluster_id')
    )
    op.create_index(op.f('ix_article_clusters_clustered_at'), 'article_clusters', ['clustered_at'], unique=False)
    op.create_table('article_cluster_articles',
    sa.Column('article_cluster_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_cluster_id'], ['article_clusters.article_cluster_id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_cluster_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_cluster_articles')
    op.drop_index(op.f('ix_article_clusters_clustered_at'), table_name='article_clusters')
    op.drop_table('article_clusters')
    # ### end Alembic commands ###
