"""explicit_none_dimension

Revision ID: 8d27d91dc1c7
Revises: cfc3bbc58f87
Create Date: 2026-01-11 22:50:46.904133

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d27d91dc1c7'
down_revision = 'cfc3bbc58f87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
