"""added story to story table

Revision ID: 98e79f7790d5
Revises: 38c40ca77dc9
Create Date: 2026-02-08 20:50:20.932680

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e79f7790d5'
down_revision = '38c40ca77dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_stories',
    sa.Column('story_id_1', sa.String(), nullable=False),
    sa.Column('story_id_2', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id_1'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['story_id_2'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id_1', 'story_id_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_stories')
    # ### end Alembic commands ###
