"""added topic and article topics tables

Revision ID: c6855603d840
Revises: 98e79f7790d5
Create Date: 2026-02-20 21:09:01.276765

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6855603d840'
down_revision = '98e79f7790d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('topic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic')
    )
    op.create_table('article_topics',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic'], ['topics.topic'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
