"""rename clustered_at to cluster_period

Revision ID: d7cd0d094a40
Revises: d89649ba52fa
Create Date: 2026-01-26 21:40:51.963102

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7cd0d094a40'
down_revision = 'd89649ba52fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_clusters', sa.Column('cluster_period', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_article_clusters_clustered_at'), table_name='article_clusters')
    op.create_index(op.f('ix_article_clusters_cluster_period'), 'article_clusters', ['cluster_period'], unique=False)
    op.drop_column('article_clusters', 'clustered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_clusters', sa.Column('clustered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_article_clusters_cluster_period'), table_name='article_clusters')
    op.create_index(op.f('ix_article_clusters_clustered_at'), 'article_clusters', ['clustered_at'], unique=False)
    op.drop_column('article_clusters', 'cluster_period')
    # ### end Alembic commands ###
