"""added story_period to stories table

Revision ID: d86eedd533e3
Revises: d7cd0d094a40
Create Date: 2026-01-26 22:40:54.481301

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86eedd533e3'
down_revision = 'd7cd0d094a40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('story_period', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_stories_story_period'), 'stories', ['story_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_story_period'), table_name='stories')
    op.drop_column('stories', 'story_period')
    # ### end Alembic commands ###
