"""add story geo fields

Revision ID: d89649ba52fa
Revises: 790ba4214468
Create Date: 2026-01-19 23:09:39.245876

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd89649ba52fa'
down_revision = '790ba4214468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('primary_location', sa.String(), nullable=True),
    sa.Column('primary_location_coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('parent_story_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_stories_primary_location_coordinates "
        "ON stories USING gist (primary_location_coordinates)"
    )
    op.create_index(op.f('ix_stories_generated_at'), 'stories', ['generated_at'], unique=False)
    op.create_index(op.f('ix_stories_updated_at'), 'stories', ['updated_at'], unique=False)
    op.create_table('article_stories',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'story_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_stories')
    op.drop_index(op.f('ix_stories_updated_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_generated_at'), table_name='stories')
    op.drop_index('idx_stories_primary_location_coordinates', table_name='stories', postgresql_using='gist')
    op.drop_table('stories')
    # ### end Alembic commands ###
