"""added story location table

Revision ID: df794d331489
Revises: 23117ec3c308
Create Date: 2026-02-02 06:31:00.693606

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df794d331489'
down_revision = '23117ec3c308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_locations',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('wikidata_qid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['wikidata_qid'], ['locations.wikidata_qid'], ),
    sa.PrimaryKeyConstraint('story_id', 'wikidata_qid')
    )
    op.drop_index(op.f('idx_stories_primary_location_coordinates'), table_name='stories', postgresql_using='gist')
    op.drop_column('stories', 'primary_location')
    op.drop_column('stories', 'primary_location_coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('primary_location_coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('primary_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_stories_primary_location_coordinates'), 'stories', ['primary_location_coordinates'], unique=False, postgresql_using='gist')
    op.drop_table('story_locations')
    # ### end Alembic commands ###
