"""add fk on story_topics topic

Revision ID: e7b62efa5f91
Revises: 328bf871adf3
Create Date: 2026-02-25 16:47:15.451620

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b62efa5f91'
down_revision = '328bf871adf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'story_topics', 'topics', ['topic'], ['topic'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_topics', type_='foreignkey')
    # ### end Alembic commands ###
