"""add kb_states table

Revision ID: e909959f2b97
Revises: b3d8f1a92c47
Create Date: 2026-05-16 14:06:30.600989

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e909959f2b97'
down_revision = 'b3d8f1a92c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_states',
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=False),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=True),
    sa.Column('capital_qid', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('subregion', sa.String(), nullable=True),
    sa.Column('un_member', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['capital_qid'], ['kb_entities.qid'], ),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.PrimaryKeyConstraint('qid'),
    sa.UniqueConstraint('iso_alpha_2'),
    sa.UniqueConstraint('iso_alpha_3')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_states')
    # ### end Alembic commands ###
