"""phase 6 additive changes

Revision ID: fb0c2a0f5b87
Revises: 149f623c3b4a
Create Date: 2026-02-25 16:44:28.132538

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0c2a0f5b87'
down_revision = '149f623c3b4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_embeddings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    op.add_column('story_articles', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_articles', 'assigned_at')
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_column('article_embeddings', 'created_at')
    # ### end Alembic commands ###
