"""add article entity mentions table

Revision ID: 17c2ed7d42ba
Revises: 58a854e79e9d
Create Date: 2026-02-25 16:39:24.090732

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c2ed7d42ba'
down_revision = '58a854e79e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_entity_mentions',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('ner_type', sa.String(), nullable=False),
    sa.Column('mention_text', sa.String(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('in_title', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'ner_type', 'mention_text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_entity_mentions')
    # ### end Alembic commands ###
