"""add resolved entity link tables

Revision ID: 58a854e79e9d
Revises: ebb8de4ab958
Create Date: 2026-02-25 16:35:33.115668

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a854e79e9d'
down_revision = 'ebb8de4ab958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_entities_resolved',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.PrimaryKeyConstraint('article_id', 'qid')
    )
    op.create_table('story_entities',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'qid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_entities')
    op.drop_table('article_entities_resolved')
    # ### end Alembic commands ###
