"""add kb entity tables

Revision ID: ebb8de4ab958
Revises: b94dfed3d14a
Create Date: 2026-02-25 16:30:38.794782

"""
from __future__ import annotations

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb8de4ab958'
down_revision = 'b94dfed3d14a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entities',
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_table('kb_entity_aliases',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('qid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.PrimaryKeyConstraint('alias', 'qid')
    )
    op.create_table('kb_locations',
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_table('kb_persons',
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('nationalities', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['qid'], ['kb_entities.qid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    op.drop_index(op.f('ix_stories_generated_at'), table_name='stories')
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.create_index(op.f('ix_stories_generated_at'), 'stories', ['created_at'], unique=False)
    op.drop_table('kb_persons')
    op.drop_table('kb_locations')
    op.drop_table('kb_entity_aliases')
    op.drop_table('kb_entities')
    # ### end Alembic commands ###
